# Mosquitto Configuration with TLS/SSL

# Port for standard MQTT (disable for TLS only)
#listener 1883
#protocol mqtt

# Port for MQTT over TLS/SSL
#listener 8883
#protocol mqtt
#cafile c:\Users\Akos\Downloads\akos_certs\certs\ca_dir\ec_ca_cert.pem
#certfile c:\Users\Akos\Downloads\akos_certs\certs\server_dir\ec_server_cert.pem
#keyfile c:\Users\Akos\Downloads\akos_certs\certs\server_dir\ec_server_private.pem
#require_certificate false

# Persistence
#persistence true
#persistence_location C:\Users\Akos\mosquitto\data\

listener 8883 0.0.0.0

cafile certs/ca_dir/ec_ca_cert.pem
certfile certs/server_dir/ec_server_cert.pem
keyfile certs/server_dir/ec_server_private.pem

require_certificate false
#use_identity_as_username true
allow_anonymous true

